### ISSUE TITLE
Cannot execute command 'cleanlight' in plugin LightCleaner v1.13.1-v1 - plugin is disabled.

### ISSUE THREAD

**Issue by uncovery** [bergerhealer/Light-Cleaner#10]
[22:54:43 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'cleanlight' in plugin LightCleaner v1.13.1-v1 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1648) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1483) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-a1f2566-282dad1]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

any idea where this comes from?
It does not seem to create a config file.
Running Spigot 1.13.2 (today's release)

**Comment by uncovery** [comment]
nevermind, the commonlib was not up to date it seems
