### ISSUE TITLE
LC seems not to like Coreprotect or FAWE, unsure

### ISSUE THREAD

**Issue by adamlaughlin** [bergerhealer/Light-Cleaner#17]
I apologize for my limited understanding, this issue may be caused by CoreProtect.  I only posted it here because I've never seen this before installing and running LC.

I've used /cleanlight world in the example below.  It's still running, albeit at around 15 TPS on a dual Xeon 4-thread server with 3GB of RAM.  I love what you did for us, but your plugin is very greedy lol!  The suggested option to fine-tune this is very much desired.  I'm really glad this plugin can be uninstalled afterwards, I am getting pretty scared it's going to corrupt my world.

05.03 15:56:01 [Server] WARN java.lang.NullPointerException
05.03 15:56:01 [Server] WARN at net.coreprotect.consumer.Process.processConsumer(Process.java:88)
05.03 15:56:01 [Server] WARN at net.coreprotect.consumer.Consumer.run(Consumer.java:122)
05.03 15:56:01 [Server] WARN at java.lang.Thread.run(Thread.java:748)
05.03 15:56:02 [Server] WARN java.lang.NullPointerException
05.03 15:56:03 [Server] WARN java.lang.NullPointerException
05.03 16:00:35 [Server] INFO (FAWE) [FAWE `tick-limiter`] Detected and cancelled physics  lag source at Location{world=CraftWorld{name=legitimus},x=7072.0,y=60.0,z=1941.0,pitch=0.0,yaw=0.0}
05.03 16:00:37 [Server] WARN java.lang.NullPointerException
05.03 16:00:38 [Server] WARN java.lang.NullPointerException
05.03 16:00:39 [Server] WARN java.lang.NullPointerException
05.03 16:00:41 [Server] WARN java.lang.NullPointerException
05.03 16:00:42 [Server] WARN java.lang.NullPointerException
05.03 16:00:44 [Server] WARN java.lang.NullPointerException
05.03 16:00:45 [Server] WARN java.lang.NullPointerException
05.03 16:00:47 [Server] WARN java.lang.NullPointerException
05.03 16:00:48 [Server] WARN java.lang.NullPointerException
05.03 16:00:49 [Server] WARN java.lang.NullPointerException
05.03 16:00:50 [Server] WARN java.lang.NullPointerException
05.03 16:00:51 [Server] WARN java.lang.NullPointerException
05.03 16:00:52 [Server] WARN java.lang.NullPointerException
05.03 16:00:53 [Server] WARN java.lang.NullPointerException
05.03 16:00:54 [Server] WARN java.lang.NullPointerException
05.03 16:00:55 [Server] WARN java.lang.NullPointerException
05.03 16:00:56 [Server] WARN java.lang.NullPointerException
05.03 16:00:57 [Server] WARN java.lang.NullPointerException
05.03 16:00:58 [Server] WARN java.lang.NullPointerException
05.03 16:00:59 [Server] WARN java.lang.NullPointerException
05.03 16:01:00 [Server] WARN java.lang.NullPointerException
05.03 16:01:01 [Server] WARN java.lang.NullPointerException
05.03 16:01:02 [Server] WARN java.lang.NullPointerException
05.03 16:01:03 [Server] WARN java.lang.NullPointerException
05.03 16:01:04 [Server] WARN java.lang.NullPointerException
05.03 16:01:05 [Server] WARN java.lang.NullPointerException
05.03 16:01:06 [Server] WARN java.lang.NullPointerException
05.03 16:01:07 [Server] WARN java.lang.NullPointerException
05.03 16:01:09 [Server] WARN java.lang.NullPointerException
05.03 16:01:10 [Server] WARN java.lang.NullPointerException
05.03 16:01:11 [Server] WARN java.lang.NullPointerException
05.03 16:01:12 [Server] WARN java.lang.NullPointerException

Update:
Getting worse, NPEs are back, into the 100's.  Aborted and uninstalled.  What went wrong?

**Comment by adamlaughlin** [comment]
Also this is not what abort means

05.03 16:19:52 [Server] INFO All pending tasks cleared, will finish current 1156 chunks now...
05.03 16:19:52 [Server] WARN java.lang.NullPointerException
05.03 16:19:53 [Server] WARN java.lang.NullPointerException
05.03 16:19:54 [Server] WARN java.lang.NullPointerException
05.03 16:19:55 [Server] WARN java.lang.NullPointerException
05.03 16:19:56 [Server] WARN java.lang.NullPointerException
05.03 16:19:57 [Server] WARN java.lang.NullPointerException
05.03 16:19:58 [Server] WARN java.lang.NullPointerException
05.03 16:19:59 [Server] WARN java.lang.NullPointerException
05.03 16:20:00 [Server] WARN java.lang.NullPointerException
05.03 16:20:01 [Server] WARN java.lang.NullPointerException
05.03 16:20:02 [Server] WARN java.lang.NullPointerException
05.03 16:20:03 [Server] WARN java.lang.NullPointerException
05.03 16:20:04 [Server] WARN java.lang.NullPointerException
05.03 16:20:05 [Server] WARN java.lang.NullPointerException
05.03 16:20:06 [Server] WARN java.lang.NullPointerException
05.03 16:20:07 [Server] WARN java.lang.NullPointerException
05.03 16:20:08 [Server] WARN java.lang.NullPointerException
05.03 16:20:09 [Server] WARN java.lang.NullPointerException
05.03 16:20:10 [Server] WARN java.lang.NullPointerException
05.03 16:20:12 [Server] WARN java.lang.NullPointerException
05.03 16:20:13 [Server] WARN java.lang.NullPointerException
05.03 16:20:14 [Server] WARN java.lang.NullPointerException
05.03 16:20:15 [Server] WARN java.lang.NullPointerException
05.03 16:20:16 [Server] WARN java.lang.NullPointerException
05.03 16:20:17 [Server] WARN java.lang.NullPointerException
05.03 16:20:18 [Server] WARN java.lang.NullPointerException
05.03 16:20:19 [Server] WARN java.lang.NullPointerException
05.03 16:20:20 [Server] WARN java.lang.NullPointerException
05.03 16:20:21 [Server] WARN java.lang.NullPointerException
05.03 16:20:22 [Server] WARN java.lang.NullPointerException
05.03 16:20:23 [Server] WARN java.lang.NullPointerException
05.03 16:20:24 [Server] WARN java.lang.NullPointerException
05.03 16:20:25 [Server] WARN java.lang.NullPointerException
05.03 16:20:26 [Server] WARN java.lang.NullPointerException
05.03 16:20:27 [Server] WARN java.lang.NullPointerException
05.03 16:20:28 [Server] WARN java.lang.NullPointerException
05.03 16:20:29 [Server] WARN java.lang.NullPointerException
05.03 16:20:30 [Server] WARN java.lang.NullPointerException
05.03 16:20:31 [Server] WARN java.lang.NullPointerException
05.03 16:20:32 [Server] WARN java.lang.NullPointerException
05.03 16:20:33 [Server] WARN java.lang.NullPointerException
05.03 16:20:34 [Server] WARN java.lang.NullPointerException
05.03 16:20:35 [Server] WARN java.lang.NullPointerException
05.03 16:20:36 [Server] WARN java.lang.NullPointerException
05.03 16:20:37 [Server] WARN java.lang.NullPointerException
05.03 16:20:38 [Server] WARN java.lang.NullPointerException
05.03 16:20:39 [Server] WARN java.lang.NullPointerException
05.03 16:20:40 [Server] WARN java.lang.NullPointerException
05.03 16:20:41 [Server] WARN java.lang.NullPointerException
05.03 16:20:42 [Server] WARN java.lang.NullPointerException
05.03 16:20:43 [Server] WARN java.lang.NullPointerException
05.03 16:20:44 [Server] WARN java.lang.NullPointerException
05.03 16:20:45 [Server] WARN java.lang.NullPointerException
05.03 16:20:46 [Server] WARN java.lang.NullPointerException
05.03 16:20:47 [Server] WARN java.lang.NullPointerException
05.03 16:20:48 [Server] WARN java.lang.NullPointerException
05.03 16:20:49 [Server] WARN java.lang.NullPointerException
05.03 16:20:50 [Server] WARN java.lang.NullPointerException
05.03 16:20:51 [Server] WARN java.lang.NullPointerException
05.03 16:20:52 [Server] WARN java.lang.NullPointerException
05.03 16:20:53 [Server] WARN java.lang.NullPointerException
05.03 16:20:54 [Server] WARN java.lang.NullPointerException
05.03 16:20:55 [Server] WARN java.lang.NullPointerException
05.03 16:20:56 [Server] WARN java.lang.NullPointerException
05.03 16:20:57 [Server] WARN java.lang.NullPointerException
05.03 16:20:58 [Server] WARN java.lang.NullPointerException
05.03 16:20:59 [Server] WARN java.lang.NullPointerException
05.03 16:21:00 [Server] WARN java.lang.NullPointerException
05.03 16:21:01 [Server] WARN java.lang.NullPointerException
05.03 16:21:02 [Server] WARN java.lang.NullPointerException
05.03 16:21:03 [Server] WARN java.lang.NullPointerException
05.03 16:21:04 [Server] WARN java.lang.NullPointerException
05.03 16:21:05 [Server] WARN java.lang.NullPointerException
05.03 16:21:06 [Server] WARN java.lang.NullPointerException
05.03 16:21:07 [Server] WARN java.lang.NullPointerException
05.03 16:21:08 [Server] WARN java.lang.NullPointerException
05.03 16:21:09 [Server] WARN java.lang.NullPointerException
05.03 16:21:10 [Server] WARN java.lang.NullPointerException
05.03 16:21:11 [Server] WARN java.lang.NullPointerException
05.03 16:21:12 [Server] WARN java.lang.NullPointerException
05.03 16:21:13 [Server] WARN java.lang.NullPointerException
05.03 16:21:14 [Server] WARN java.lang.NullPointerException
05.03 16:21:15 [Server] WARN java.lang.NullPointerException
05.03 16:21:16 [Server] WARN java.lang.NullPointerException
05.03 16:21:17 [Server] WARN java.lang.NullPointerException
05.03 16:21:18 [Server] WARN java.lang.NullPointerException
05.03 16:21:19 [Server] WARN java.lang.NullPointerException
05.03 16:21:20 [Server] WARN java.lang.NullPointerException
05.03 16:21:21 [Server] WARN java.lang.NullPointerException
05.03 16:21:22 [Server] WARN java.lang.NullPointerException
05.03 16:21:23 [Server] WARN java.lang.NullPointerException
05.03 16:21:24 [Server] WARN java.lang.NullPointerException
05.03 16:21:25 [Server] WARN java.lang.NullPointerException
05.03 16:21:26 [Server] WARN java.lang.NullPointerException
05.03 16:21:27 [Server] WARN java.lang.NullPointerException
05.03 16:21:28 [Server] WARN java.lang.NullPointerException
05.03 16:21:29 [Server] WARN java.lang.NullPointerException
05.03 16:21:30 [Server] WARN java.lang.NullPointerException
05.03 16:21:31 [Server] WARN java.lang.NullPointerException
05.03 16:21:32 [Server] WARN java.lang.NullPointerException
05.03 16:21:33 [Server] WARN java.lang.NullPointerException
05.03 16:21:34 [Server] WARN java.lang.NullPointerException
05.03 16:21:35 [Server] WARN java.lang.NullPointerException
05.03 16:21:36 [Server] WARN java.lang.NullPointerException
05.03 16:21:37 [Server] WARN java.lang.NullPointerException
05.03 16:21:38 [Server] WARN java.lang.NullPointerException
05.03 16:21:39 [Server] WARN java.lang.NullPointerException
05.03 16:21:40 [Server] WARN java.lang.NullPointerException
05.03 16:21:41 [Server] WARN java.lang.NullPointerException
05.03 16:21:42 [Server] WARN java.lang.NullPointerException
05.03 16:21:43 [Server] WARN java.lang.NullPointerException
05.03 16:21:44 [Server] WARN java.lang.NullPointerException
05.03 16:21:45 [Server] WARN java.lang.NullPointerException
05.03 16:21:46 [Server] WARN java.lang.NullPointerException
05.03 16:21:47 [Server] WARN java.lang.NullPointerException
05.03 16:21:48 [Server] WARN java.lang.NullPointerException
05.03 16:21:49 [Server] WARN java.lang.NullPointerException
05.03 16:21:50 [Server] WARN java.lang.NullPointerException
05.03 16:21:51 [Server] WARN java.lang.NullPointerException
05.03 16:21:52 [Server] WARN java.lang.NullPointerException
05.03 16:21:53 [Server] WARN java.lang.NullPointerException
05.03 16:21:54 [Server] WARN java.lang.NullPointerException
05.03 16:21:55 [Server] WARN java.lang.NullPointerException
05.03 16:21:56 [Server] WARN java.lang.NullPointerException
05.03 16:21:57 [Server] WARN java.lang.NullPointerException
05.03 16:21:58 [Server] WARN java.lang.NullPointerException
05.03 16:21:59 [Server] WARN java.lang.NullPointerException
05.03 16:22:00 [Server] WARN java.lang.NullPointerException
05.03 16:22:01 [Server] WARN java.lang.NullPointerException
05.03 16:22:02 [Server] WARN java.lang.NullPointerException
05.03 16:22:03 [Server] WARN java.lang.NullPointerException
05.03 16:22:04 [Server] WARN java.lang.NullPointerException
05.03 16:22:05 [Server] WARN java.lang.NullPointerException
05.03 16:22:06 [Server] WARN java.lang.NullPointerException
05.03 16:22:07 [Server] WARN java.lang.NullPointerException
05.03 16:22:08 [Server] WARN java.lang.NullPointerException
05.03 16:22:09 [Server] WARN java.lang.NullPointerException
05.03 16:22:10 [Server] WARN java.lang.NullPointerException
05.03 16:22:11 [Server] WARN java.lang.NullPointerException
05.03 16:22:12 [Server] WARN java.lang.NullPointerException
05.03 16:22:13 [Server] WARN java.lang.NullPointerException
05.03 16:22:14 [Server] WARN java.lang.NullPointerException
05.03 16:22:15 [Server] WARN java.lang.NullPointerException
05.03 16:22:16 [Server] WARN java.lang.NullPointerException
05.03 16:22:17 [Server] WARN java.lang.NullPointerException
05.03 16:22:18 [Server] WARN java.lang.NullPointerException
05.03 16:22:19 [Server] WARN java.lang.NullPointerException
05.03 16:22:20 [Server] WARN java.lang.NullPointerException
05.03 16:22:21 [Server] WARN java.lang.NullPointerException
05.03 16:22:22 [Server] WARN java.lang.NullPointerException
05.03 16:22:23 [Server] WARN java.lang.NullPointerException
05.03 16:22:24 [Server] WARN java.lang.NullPointerException
05.03 16:22:25 [Server] WARN java.lang.NullPointerException
05.03 16:22:26 [Server] WARN java.lang.NullPointerException
05.03 16:22:27 [Server] WARN java.lang.NullPointerException
05.03 16:22:28 [Server] WARN java.lang.NullPointerException
05.03 16:22:29 [Server] WARN java.lang.NullPointerException
05.03 16:22:30 [Server] WARN java.lang.NullPointerException
05.03 16:22:31 [Server] WARN java.lang.NullPointerException

**Comment by adamlaughlin** [comment]
Yeah it's Dynmap.  You and your plugin are awesome.  I'll bother mikeprimm about it.
TPS is way up too.  I'm instabreaking a few thousand blocks and it's at 19.8 with cleanlight world running.

**Comment by adamlaughlin** [comment]
Actually no, it's back again without Dynmap, if it matters.  NPEs, once per second on latest version of PaperMC.
