### ISSUE TITLE
Error when /clearlight status

### ISSUE THREAD

**Issue by TheCalypso** [bergerhealer/Light-Cleaner#28]
Hello, I just ran the / clearlight command and everything went very well. The lights have been recalculated. But when I do / clearlight status I got an error message. Here it is :

[14:58:44 INFO]: TheCalypso issued server command: /cleanlight
[14:58:45 INFO]: TheCalypso issued server command: /cleanlight status
[14:58:45 ERROR]: [BKCommonLib] [BKCommonLib] Unhandled exception executing command 'cleanlight' in plugin LightCleaner v1.16.1-v1
[14:58:45 WARN]: java.lang.NullPointerException
[14:58:45 WARN]:        at com.bergerkiller.bukkit.lightcleaner.lighting.LightingTaskBatch.getStatus(LightingTaskBatch.java:98)
[14:58:45 WARN]:        at com.bergerkiller.bukkit.lightcleaner.lighting.LightingService.getCurrentStatus(LightingService.java:99)
[14:58:45 WARN]:        at com.bergerkiller.bukkit.lightcleaner.LightCleaner.command(LightCleaner.java:165)
[14:58:45 WARN]:        at com.bergerkiller.bukkit.common.PluginBase.onCommand(PluginBase.java:902)
[14:58:45 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:58:45 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[14:58:45 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[14:58:45 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1912)
[14:58:45 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1723)
[14:58:45 WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[14:58:45 WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[14:58:45 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[14:58:45 WARN]:        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[14:58:45 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[14:58:45 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[14:58:45 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[14:58:45 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136)
[14:58:45 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129)
[14:58:45 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[14:58:45 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1203)
[14:58:45 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[14:58:45 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[14:58:45 WARN]:        at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by bergerkiller** [comment]
Looks like a timing issue, the scheduler thread stop-start logic can use some improving. Probably doing a clean for a small area elsewhere gets it out of this glitched state. I'll at least fix the error though.
