### ISSUE TITLE
Spigot 1.16.2 server crash and hangs 

### ISSUE THREAD

**Issue by Tsoccerguy3** [bergerhealer/Light-Cleaner#29]
[latest.zip](https://github.com/bergerhealer/Light-Cleaner/files/5075108/latest.zip)

I issued /cleanlight command using the new BKCommonLib-1.16.2-v1-SNAPSHOT with the LightCleaner-1.16.1-v2-SNAPSHOT . this sometimes crashes the server , but not always

**Comment by bergerkiller** [comment]
Looks like a loop trying to load chunks, will look into it

**Comment by Tsoccerguy3** [comment]
I tried the new BKCommonLib snapshot I did not crash but got this error

[14:56:46] [Server thread/INFO]: MajorPayne181 issued server command: /cleanlight
[14:56:46] [Server thread/ERROR]: [BKCommonLib] Unhandled exception executing command 'cleanlight' in plugin LightCleaner v1.16.1-v2-SNAPSHOT
[14:56:46] [Server thread/WARN]: java.lang.NullPointerException
[14:56:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.utils.CommonUtil.hasPermission(CommonUtil.java:271)
[14:56:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.permissions.PermissionEnum.has(PermissionEnum.java:144)
[14:56:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.lightcleaner.lighting.LightingService$ScheduleArguments.handleCommandInput(LightingService.java:756)
[14:56:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.lightcleaner.LightCleaner.command(LightCleaner.java:198)
[14:56:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.PluginBase.onCommand(PluginBase.java:870)
[14:56:46] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:56:46] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[14:56:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:756)
[14:56:46] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1697)
[14:56:46] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1540)
[14:56:46] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
[14:56:46] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[14:56:46] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[14:56:46] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils$$Lambda$5371/1055741170.run(Unknown Source)
[14:56:46] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
[14:56:46] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144)
[14:56:46] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[14:56:46] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118)
[14:56:46] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941)
[14:56:46] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934)
[14:56:46] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[14:56:46] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918)
[14:56:46] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850)
[14:56:46] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
[14:56:46] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer$$Lambda$3205/995364892.run(Unknown Source)
[14:56:46] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[14:57:08] [Server thread/INFO]: MajorPayne181 lost connection: Disconnected
[14:57:08] [Server thread/INFO]: MajorPayne181 left the game

**Comment by bergerkiller** [comment]
The plugin snapshots for bkcommonlib are a bit unstable as I was making very large internal changes. Can you check using the latest 1.16.2 bkc build? (yes, it supports 1.16.1) https://ci.mg-dev.eu/job/BKCommonLib/867/

**Comment by Tsoccerguy3** [comment]
tested and no error

**Comment by bergerkiller** [comment]
I think I've found and fixed the server crash you've encountered, see if it's better now. Also fixes slabs/stairs letting light through.

https://ci.mg-dev.eu/job/BKCommonLib/869/
https://ci.mg-dev.eu/job/Light-Cleaner/79/
