### ISSUE TITLE
Shroomlight lighting disabled by cleanlight

### ISSUE THREAD

**Issue by leviem1** [bergerhealer/Light-Cleaner#30]
When running `/cleanlight` near Shroomlights, their lighting effect is disabled entirely.

PaperMC: git-paper-134 (1.16.1)
LightCleaner: 1.16.2-v1-SNAPSHOT (Build 79)
BKCommonLib: 1.16.2-v1-SNAPSHOT (Build 869)

**Comment by bergerkiller** [comment]
Interesting, I think it's because the block itself is opaque, so as a result it thinks it shouldnt spread the light to neighbouring blocks. It's the same for Glowstone and etc. Will look into it.

**Comment by bergerkiller** [comment]
https://ci.mg-dev.eu/job/Light-Cleaner/80/ this should fix this hopefully

**Comment by leviem1** [comment]
Every Java programmer's favorite:

```
[20:54:04 ERROR]: [LightCleaner] Failed to process task: Cleaning 441 chunks near x=16 z=160
java.lang.ArrayIndexOutOfBoundsException: Index 15994 out of bounds for length 4096
        at com.bergerkiller.bukkit.lightcleaner.util.BlockFaceSetSection.get(BlockFaceSetSection.java:16) ~[?:?]
        at com.bergerkiller.bukkit.lightcleaner.lighting.LightingChunkSection.getOpaqueFaces(LightingChunkSection.java:105) ~[?:?]
        at com.bergerkiller.bukkit.lightcleaner.lighting.LightingChunk.trySpreadBlockLightWithin(LightingChunk.java:263) ~[?:?]
        at com.bergerkiller.bukkit.lightcleaner.lighting.LightingChunk.spreadBlockLight(LightingChunk.java:231) ~[?:?]
        at com.bergerkiller.bukkit.lightcleaner.lighting.LightingCategory$2.initialize(LightingCategory.java:112) ~[?:?]
        at com.bergerkiller.bukkit.lightcleaner.lighting.LightingTaskBatch.fix(LightingTaskBatch.java:442) ~[?:?]
        at com.bergerkiller.bukkit.lightcleaner.lighting.LightingTaskBatch.process(LightingTaskBatch.java:353) ~[?:?]
        at com.bergerkiller.bukkit.lightcleaner.lighting.LightingService.run(LightingService.java:541) ~[?:?]
        at com.bergerkiller.bukkit.common.AsyncTask$1.run(AsyncTask.java:47) ~[?:?]
```

**Comment by bergerkiller** [comment]
Whoops, should've tested on a world with y higher than 15 rather than a flatworld. https://ci.mg-dev.eu/job/Light-Cleaner/81/

**Comment by leviem1** [comment]
Looking good! Fixed the opaque blocks, no other lighting errors that I can see!

On a side note, do you need some unit tests? I can't make any promises but I've been looking for a project to work on. Might be pretty beneficial to BKCommonLib.

**Comment by bergerkiller** [comment]
BKCommonLib has a lot of unit tests, but there can always be more! Light cleaner is the one with very little unit tests, but that's in part because it requires world access to do most of the logic. To unit test all that, the plugin needs to be rewritten in a more abstract way, and that might lead to a loss in performance.

It's a bit of a tradeoff
