### ISSUE TITLE
No permission error

### ISSUE THREAD

**Issue by x1p** [bergerhealer/Light-Cleaner#39]
When a staff member without the proper permission executes /cleanlight, a nasty looking error appears.
Perhaps this could be replaced with something more delicate?

```
cleanlight 1
[Server thread/ERROR]: [BKCommonLib] [BKCommonLib] Unhandled exception executing command 'cleanlight' in plugin LightCleaner v1.16.4-v2-SNAPSHOT
[Server thread/WARN]: java.lang.IllegalArgumentException: This permission requires 0 arguments, but 1 were provided
[Server thread/WARN]: at com.bergerkiller.bukkit.common.permissions.IPermissionEnum.has(IPermissionEnum.java:69)
[Server thread/WARN]: at com.bergerkiller.bukkit.common.permissions.PermissionEnum.has(PermissionEnum.java:134)
[Server thread/WARN]: at com.bergerkiller.bukkit.lightcleaner.lighting.LightingService$ScheduleArguments.checkRadiusPermission(LightingService.java:834)
[Server thread/WARN]: at com.bergerkiller.bukkit.lightcleaner.lighting.LightingService$ScheduleArguments.handleCommandInput(LightingService.java:908)
[Server thread/WARN]: at com.bergerkiller.bukkit.lightcleaner.LightCleaner.command(LightCleaner.java:263)
[Server thread/WARN]: at com.bergerkiller.bukkit.common.PluginBase.onCommand(PluginBase.java:870)
[Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807)
[Server thread/WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2074)
[Server thread/WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1877)
[Server thread/WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1830)
[Server thread/WARN]: at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47)
[Server thread/WARN]: at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5)
[Server thread/WARN]: at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
[Server thread/WARN]: at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[Server thread/WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[Server thread/WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[Server thread/WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1207)
[Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1200)
[Server thread/WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1176)
[Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1020)
[Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:180)
[Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
```

BKCommonLib build 978
LightCleaner build 104
Paper 1.16.4

**Comment by bergerkiller** [comment]
Try with bkc 982, as I broke something recently that was also fixed then again recently https://ci.mg-dev.eu/job/BKCommonLib/982/

**Comment by x1p** [comment]
👍
