### ISSUE TITLE
java.lang.IllegalArgumentException: The handle can not be null

### ISSUE THREAD

**Issue by bergerkiller** [bergerhealer/Light-Cleaner#42]
When the auto-clean handler of FAWE runs, this error occurs:

```
[14:50:15] [pool-146-thread-3/WARN]: java.lang.IllegalArgumentException: The handle can not be null
[14:50:15] [pool-146-thread-3/WARN]: 	at com.bergerkiller.bukkit.common.wrappers.BasicWrapper.setHandle(BasicWrapper.java:21)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.bergerkiller.bukkit.common.wrappers.LongHashSet.<init>(LongHashSet.java:24)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.bergerkiller.bukkit.lightcleaner.lighting.LightingAutoClean.schedule(LightingAutoClean.java:77)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.bergerkiller.bukkit.lightcleaner.impl.FastAsyncWorldEditHandler$1.processSet(FastAsyncWorldEditHandler.java:53)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.processors.MultiBatchProcessor.processSet(MultiBatchProcessor.java:117)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.processors.MultiBatchProcessor.processSet(MultiBatchProcessor.java:97)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:928)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:916)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:33)
[14:50:15] [pool-146-thread-3/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:50:15] [pool-146-thread-3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:50:15] [pool-146-thread-3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:50:15] [pool-146-thread-3/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:50:15] [pool-146-thread-3/WARN]: java.lang.IllegalArgumentException: The handle can not be null
[14:50:15] [pool-146-thread-3/WARN]: 	at com.bergerkiller.bukkit.common.wrappers.BasicWrapper.setHandle(BasicWrapper.java:21)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.bergerkiller.bukkit.common.wrappers.LongHashSet.<init>(LongHashSet.java:24)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.bergerkiller.bukkit.lightcleaner.lighting.LightingAutoClean.schedule(LightingAutoClean.java:77)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.bergerkiller.bukkit.lightcleaner.impl.FastAsyncWorldEditHandler$1.processSet(FastAsyncWorldEditHandler.java:53)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.processors.MultiBatchProcessor.processSet(MultiBatchProcessor.java:117)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.processors.MultiBatchProcessor.processSet(MultiBatchProcessor.java:97)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.processors.BatchProcessorHolder.processSet(BatchProcessorHolder.java:26)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:928)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:916)
[14:50:15] [pool-146-thread-3/WARN]: 	at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.call(ChunkHolder.java:33)
[14:50:15] [pool-146-thread-3/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:50:15] [pool-146-thread-3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:50:15] [pool-146-thread-3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:50:15] [pool-146-thread-3/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

- Spigot/Paper Version Number (/version): This server is running CraftBukkit version 2991-Spigot-018b9a0-f3f3094 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
- Minecraft Version: [e.g. 1.16.5]: 1.16.5

**Comment by bergerkiller** [comment]
I need a little more information about the version of LightCleaner and BKCommonLib used here.

The error occurs when initializing a new LongHashSet, which is impossible, unless earlier on something else went wrong. Are there errors by BKCommonLib at startup? Could this be /reload related?

**Comment by Vilican** [comment]
I don't see error BKCommonLib at startup. Also, we don't use /reload command as it causes problems with many other plugins.

**Comment by bergerkiller** [comment]
Does the error happen all the time (every restart) or was this a one-time occurrence?

**Comment by LaurenceBarnes** [comment]
the BKCommonLib version is definitely not the most recent one, I'd suggest if you test with that one again (#1000 from jenkins)

**Comment by bergerkiller** [comment]
Quite unlikely the #1000 one will fix this particular issue though, that only has some support fixes for some custom server types (which vilican isnt using)

**Comment by LaurenceBarnes** [comment]
well, you never know if "collateral fixes" happen xD
but yeah, I hope both of you can figure it out :D

**Comment by Vilican** [comment]
This particular message does not appear during start, but more like randomly - I think it's tied to some event (or more), but haven't determined which yet.

Oh, and I see, I will try with the updated version and I will let you know if the issue persists.
