### ISSUE TITLE
PermissionDefaults.yml is generating broken.

### ISSUE THREAD

**Issue by mibby** [bergerhealer/Light-Cleaner#43]
BKCommonLib dev 1034
LightCleaner dev 108

@bergerkiller PermissionDefaults.yml is generating broken.

```
[02:00:18] [Server thread/INFO]: [LightCleaner] Enabling LightCleaner v1.16.5-v1
[02:00:18] [Server thread/ERROR]: [BKCommonLib.Configuration] [BKCommonLib] [Configuration] An error occured while loading file 'plugins/LightCleaner/Localization.yml'
[02:00:18] [Server thread/ERROR]: [BKCommonLib.Configuration] [BKCommonLib] [Configuration] A backup of this (corrupted?) file named 'Localization.yml.old' can be found in case you wish to restore
org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 6, column 3:
      cleanlight:
      ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 15, column 5:
        noperm: §cYou don't have permiss ... 
        ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:617) ~[patched_1.16.5.jar:"]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165) ~[patched_1.16.5.jar:"]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59) ~[patched_1.16.5.jar:"]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45) ~[patched_1.16.5.jar:"]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140) ~[patched_1.16.5.jar:"]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119) ~[patched_1.16.5.jar:"]
	at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:221) ~[patched_1.16.5.jar:"]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:191) ~[patched_1.16.5.jar:"]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[patched_1.16.5.jar:"]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[patched_1.16.5.jar:"]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[patched_1.16.5.jar:"]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[patched_1.16.5.jar:"]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[patched_1.16.5.jar:"]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[patched_1.16.5.jar:"]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[patched_1.16.5.jar:"]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[patched_1.16.5.jar:"]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115) ~[patched_1.16.5.jar:"]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:146) ~[patched_1.16.5.jar:"]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151) ~[patched_1.16.5.jar:"]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[patched_1.16.5.jar:"]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:442) ~[patched_1.16.5.jar:"]
	at com.bergerkiller.bukkit.common.config.yaml.YamlDeserializer.deserialize(YamlDeserializer.java:69) ~[?:?]
	at com.bergerkiller.bukkit.common.config.yaml.YamlNodeAbstract.loadFromReader(YamlNodeAbstract.java:793) ~[?:?]
	at com.bergerkiller.bukkit.common.config.yaml.YamlNodeAbstract.loadFromStream(YamlNodeAbstract.java:780) ~[?:?]
	at com.bergerkiller.bukkit.common.config.FileConfiguration.load(FileConfiguration.java:97) ~[?:?]
	at com.bergerkiller.bukkit.common.PluginBase.loadLocalization(PluginBase.java:937) ~[?:?]
	at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:711) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:582) ~[patched_1.16.5.jar:"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:302) ~[patched_1.16.5.jar:"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1064) ~[patched_1.16.5.jar:"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[02:00:18] [Thread-18/INFO]: [BKCommonLib.Configuration] [BKCommonLib] [Configuration] File 'plugins/LightCleaner/PermissionDefaults.yml' has been generated
[02:00:18] [Server thread/INFO]: [LightCleaner] Added support for automatic light cleaning when FastAsyncWorldEdit operations are performed!
[02:00:18] [Server thread/INFO]: [LightCleaner] LightCleaner version 1.16.5-v1 (build: 108) enabled! (0.335s)
```

```
#> Below are the default permissions set for plugin 'LightCleaner'.
#> These permissions are ignored if the permission is set for a group or player.
#> Use the defaults as a base to keep the permissions file small
#> Need help with this file? Please visit:
#> https://dev.bukkit.org/projects/bkcommonlib/pages/general/permission-defaults
lightcleaner:
  clean:
    view:
      default: op
      
description: Allows a player to fix lighting issues in chunks around the player
        within view ra    any:
      default: op
      
    description: Allows a player to fix lighting issues in chunks around the player
        with any ra    radius:
      *:
        default: op
        
    description: 'Allows a player to only fix a specific radius of chunks (example
          perm: lightcleaner.clean.radi    world:
      default: op
      
      description: Allows a player to fix lighting issues in all the chunks of an
        entire w    at:
      default: op
      
    description: Allows a player to specify coordinates to c  status:
    default: op
    
    description: Allows a player to check the status of ongoing lighting operatio  abort:
    default: op
    
  description: Allows a player to abort all current lighting operatio  pause:
    default: op
    
  description: Allows a player to pause and resume lighting operatio  dirty:
    debug:
      default: false
      
  description: Allows a player to corrupt lighting instead of clean it (for debugging
        purpo  block:
    debug:
      default: op
      
    description: Allows a player to mark blocks that will make light cleaner log
        the light level gener
```

**Comment by bergerkiller** [comment]
Can you upload the exact contents of Localization.yml to https://paste.traincarts.net ? The text is a bit messed up in the code block due to word wrap among other things.

**Comment by mibby** [comment]
PermissionsDefaults
https://paste.traincarts.net/qomewuxufi.shell

Localization
https://paste.traincarts.net/dagaqopojo.shell

**Comment by bergerkiller** [comment]
Can you set `forceSynchronousSaving` to true in BKCommonLib's config.yml? Does that change anything? It seems like some sort of corruptions occurred when saving that I can't really explain by the yaml lib alone.
