### ISSUE TITLE
UnsupportedOperationException: World does not store block light data

### ISSUE THREAD

**Issue by bladedev** [bergerhealer/Light-Cleaner#46]
When running any `/clearlight` commands (except from status and abort), the following error spams the console for every chunk the plugin tries to update:
```
java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException: World does not store block light data
[15:30:28 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
[15:30:28 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
[15:30:28 WARN]:        at java.base/java.util.concurrent.CompletableFuture$BiRelay.tryFire(Unknown Source)
[15:30:28 WARN]:        at java.base/java.util.concurrent.CompletableFuture$CoCompletion.tryFire(Unknown Source)
[15:30:28 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
[15:30:28 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
[15:30:28 WARN]:        at BKCommonLib-1.17.1-v2-1111.jar//com.bergerkiller.bukkit.common.internal.logic.LightingHandler_1_14$EngineUpdateTaskLists.lambda$postRun$0(LightingHandler_1_14.java:257)
[15:30:28 WARN]:        at BKCommonLib-1.17.1-v2-1111.jar//com.bergerkiller.bukkit.common.internal.CommonNextTickExecutor$ExecutorTask.run(CommonNextTickExecutor.java:164)
[15:30:28 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:30:28 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[15:30:28 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1579)
[15:30:28 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:493)
[15:30:28 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1494)
[15:30:28 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1284)
[15:30:28 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[15:30:28 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[15:30:28 WARN]: Caused by: java.lang.UnsupportedOperationException: World does not store block light data
[15:30:28 WARN]:        at BKCommonLib-1.17.1-v2-1111.jar//com.bergerkiller.bukkit.common.internal.logic.LightingHandler_1_14$1.run(LightingHandler_1_14.java:185)
[15:30:28 WARN]:        at BKCommonLib-1.17.1-v2-1111.jar//com.bergerkiller.bukkit.common.internal.logic.LightingHandler_1_14$EngineUpdateTaskLists.preRun(LightingHandler_1_14.java:243)
[15:30:28 WARN]:        at java.base/java.util.ArrayList.forEach(Unknown Source)
[15:30:28 WARN]:        at net.minecraft.server.level.LightEngineThreaded.e(LightEngineThreaded.java:521)
[15:30:28 WARN]:        at net.minecraft.server.level.LightEngineThreaded.lambda$tryScheduleUpdate$27(LightEngineThreaded.java:508)
[15:30:28 WARN]:        at net.minecraft.util.thread.ThreadedMailbox.g(ThreadedMailbox.java:87)
[15:30:28 WARN]:        at net.minecraft.util.thread.ThreadedMailbox.a(ThreadedMailbox.java:141)
[15:30:28 WARN]:        at net.minecraft.util.thread.ThreadedMailbox.run(ThreadedMailbox.java:96)
[15:30:28 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[15:30:28 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[15:30:28 WARN]:        ... 1 more
[15:30:28 ERROR]: [LightCleaner] Failed to apply lighting data for [x=4848 z=-5376 count=1156]
java.lang.UnsupportedOperationException: World does not store block light data
        at com.bergerkiller.bukkit.common.internal.logic.LightingHandler_1_14$1.run(LightingHandler_1_14.java:185) ~[BKCommonLib-1.17.1-v2-1111.jar:?]
        at com.bergerkiller.bukkit.common.internal.logic.LightingHandler_1_14$EngineUpdateTaskLists.preRun(LightingHandler_1_14.java:243) ~[BKCommonLib-1.17.1-v2-1111.jar:?]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
        at net.minecraft.server.level.LightEngineThreaded.e(LightEngineThreaded.java:521) ~[patched_1.17.1.jar:git-Purpur-1350]
        at net.minecraft.server.level.LightEngineThreaded.lambda$tryScheduleUpdate$27(LightEngineThreaded.java:508) ~[patched_1.17.1.jar:git-Purpur-1350]
        at net.minecraft.util.thread.ThreadedMailbox.g(ThreadedMailbox.java:87) ~[patched_1.17.1.jar:git-Purpur-1350]
        at net.minecraft.util.thread.ThreadedMailbox.a(ThreadedMailbox.java:141) ~[patched_1.17.1.jar:git-Purpur-1350]
        at net.minecraft.util.thread.ThreadedMailbox.run(ThreadedMailbox.java:96) ~[patched_1.17.1.jar:git-Purpur-1350]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
```
This is the output of `/clearlight version`:
```
LightCleaner: v1.17.1-v1 (build: 117)
BKCommonLib: v1.17.1-v2 (build: 1111)
Server: git-Purpur-1350 (MC: 1.17.1)
```

I'm guessing it has something to do with Purpur, but I'm not completely sure.

**Comment by bergerkiller** [comment]
Was already fixed today https://ci.mg-dev.eu/job/BKCommonLib/1114/

**Comment by bladedev** [comment]
Works great now, thanks!
