### ISSUE TITLE
Mohist Error when using /cleanlight

### ISSUE THREAD

**Issue by Eisenbahn** [bergerhealer/Light-Cleaner#56]
Hi,
Using Mohist
![image](https://user-images.githubusercontent.com/2753064/205198925-85a11ed9-f005-46dc-bbfc-5d104a2c01a1.png)

BKCommonLib-1.19.2-v3-1410.jar
LightCleaner-1.19-v1-141.jar

Nothing happens when i try fixing the lights around

I'm having issues with 
LightCleaner-1.16.5-v1
BKCommonLib-1.16.5-v3-1043
too

But the issue only happens in this particular server (Pixelmon). Using the 1.16.5~ versions fix the lights

`[02:07:16] [Thread-80/ERROR] [Mohist]: [LightCleaner] Error while processing
java.lang.NoClassDefFoundError: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_221]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_221]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598) ~[?:1.8.0_221]
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677) ~[?:1.8.0_221]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735) ~[?:1.8.0_221]
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714) ~[?:1.8.0_221]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:1.8.0_221]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_221]
	at com.bergerkiller.bukkit.lightcleaner.lighting.LightingChunk.fill(LightingChunk.java:164) ~[?:?]
	at com.bergerkiller.bukkit.lightcleaner.lighting.LightingTaskBatch.lambda$onChunkLoaded$3(LightingTaskBatch.java:312) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[CraftTask.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:422) ~[CraftScheduler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_221]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.bergerkiller.bukkit.common.wrappers.BlockDataRegistry
	at com.bergerkiller.bukkit.common.conversion.type.WrapperConversion.toBlockData(WrapperConversion.java:419) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen33c6529.invoke(Unknown Source) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.InitInvoker.invoke(InitInvoker.java:90) ~[?:?]
	at com.bergerkiller.mountiplex.conversion.type.AnnotatedConverter.convertInput(AnnotatedConverter.java:50) ~[?:?]
	at com.bergerkiller.mountiplex.conversion.Converter.apply(Converter.java:71) ~[?:?]
	at com.bergerkiller.mountiplex.conversion.util.ParamsConverterList.convertResult(ParamsConverterList.java:84) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.declarations.Template$Method$Converted.invoke(Template.java:1691) ~[?:?]
	at com.bergerkiller.generated.net.minecraft.world.level.chunk.DataPaletteBlockHandle$impl.getBlockData(Unknown Source) ~[?:?]
	at com.bergerkiller.bukkit.common.wrappers.ChunkSection.getBlockData(ChunkSection.java:42) ~[?:?]
	at com.bergerkiller.bukkit.lightcleaner.lighting.LightingCube.<init>(LightingCube.java:72) ~[?:?]
	at com.bergerkiller.bukkit.lightcleaner.lighting.LightingCube.<init>(LightingCube.java:22) ~[?:?]
	at com.bergerkiller.bukkit.lightcleaner.lighting.LightingCube$Data.build(LightingCube.java:401) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_221]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_221]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_221]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_221]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747) ~[?:1.8.0_221]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721) ~[?:1.8.0_221]
	at java.util.stream.AbstractTask.compute(AbstractTask.java:316) ~[?:1.8.0_221]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_221]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_221]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_221]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_221]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_221]
`

**Comment by bergerkiller** [comment]
Is there any other errors from [LightCleaner] or [BKCommonLib] that are reported earlier in the log / at startup?

**Comment by Eisenbahn** [comment]
Yes:

1st BKC Error:

`[10:53:40] [Server thread/ERROR] [Mohist]: [BKCommonLib] An error occurred while loading
java.lang.RuntimeException: An error occurred trying to initialize class 'com.bergerkiller.bukkit.common.utils.RecipeUtil':
	at com.bergerkiller.bukkit.common.Common.loadClasses(Common.java:156) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.bukkit.common.internal.CommonClasses.loadCommon(CommonClasses.java:85) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.bukkit.common.internal.CommonClasses.loadUtil(CommonClasses.java:78) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.bukkit.common.internal.CommonClasses.init(CommonClasses.java:58) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.bukkit.common.internal.CommonPlugin.onLoad(CommonPlugin.java:523) [BKCommonLib-1.19.2-v3-1410.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:397) [CraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:339) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:315) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.ExceptionInInitializerError
	at com.bergerkiller.bukkit.common.wrappers.BlockDataRegistry.fromMaterial(BlockDataRegistry.java:109) ~[?:?]
	at com.bergerkiller.bukkit.common.wrappers.BlockDataRegistry.<clinit>(BlockDataRegistry.java:19) ~[?:?]
	at com.bergerkiller.bukkit.common.utils.RecipeUtil.<clinit>(RecipeUtil.java:47) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_221]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_221]
	at com.mohistmc.bukkit.nms.proxy.ProxyClass.forName(ProxyClass.java:21) ~[ProxyClass.class:?]
	at com.mohistmc.bukkit.nms.proxy.ProxyClass.forName(ProxyClass.java:16) ~[ProxyClass.class:?]
	at com.bergerkiller.bukkit.common.Common.loadClasses(Common.java:154) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	... 9 more
Caused by: java.lang.NullPointerException
	at com.bergerkiller.bukkit.common.internal.legacy.IBlockDataToMaterialData.createMaterialData(IBlockDataToMaterialData.java:671) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mplgen6422c6e7.getMaterialData(GeneratedCodeInvoker$mplgen6422c6e7.java) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mplgen6422c6e7.invoke(GeneratedCodeInvoker$mplgen6422c6e7.java) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:155) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.legacy.IBlockDataToMaterialData.getMaterialData(IBlockDataToMaterialData.java:647) ~[?:?]
	at com.bergerkiller.bukkit.common.wrappers.BlockDataImpl.refreshBlock(BlockDataImpl.java:319) ~[?:?]
	at com.bergerkiller.bukkit.common.wrappers.BlockDataImpl.<init>(BlockDataImpl.java:292) ~[?:?]
	at com.bergerkiller.bukkit.common.wrappers.BlockDataImpl.<init>(BlockDataImpl.java:286) ~[?:?]
	at com.bergerkiller.bukkit.common.wrappers.BlockDataImpl$BlockDataConstant.<init>(BlockDataImpl.java:254) ~[?:?]
	at com.bergerkiller.bukkit.common.wrappers.BlockDataImpl.<clinit>(BlockDataImpl.java:104) ~[?:?]
	at com.bergerkiller.bukkit.common.wrappers.BlockDataRegistry.fromMaterial(BlockDataRegistry.java:109) ~[?:?]
	at com.bergerkiller.bukkit.common.wrappers.BlockDataRegistry.<clinit>(BlockDataRegistry.java:19) ~[?:?]
	at com.bergerkiller.bukkit.common.utils.RecipeUtil.<clinit>(RecipeUtil.java:47) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_221]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_221]
	at com.mohistmc.bukkit.nms.proxy.ProxyClass.forName(ProxyClass.java:21) ~[ProxyClass.class:?]
	at com.mohistmc.bukkit.nms.proxy.ProxyClass.forName(ProxyClass.java:16) ~[ProxyClass.class:?]
	at com.bergerkiller.bukkit.common.Common.loadClasses(Common.java:154) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	... 9 more
`


2nd BKC Error:
`[10:53:42] [Server thread/INFO] [Mohist]: Enabling BKCommonLib v1.19.2-v3
[10:53:42] [Server thread/INFO] [Mohist]: [BKCommonLib] BKCommonLib is running on Mohist (git-Mohist-1.12.2-320) : v1_12_R1 (Minecraft 1.12.2)
[10:53:42] [Server thread/INFO] [Mohist]: Now using the ProtocolLib library to provide Packet Listener and Monitor support
[10:53:43] [Server thread/ERROR] [Mohist]: Failed to enable component '[1.8 AND LATER]' of BKCommonLib.BlockDataWrapperHook
java.lang.NoClassDefFoundError: Could not initialize class com.bergerkiller.bukkit.common.wrappers.BlockDataRegistry
	at com.bergerkiller.bukkit.common.internal.logic.BlockDataWrapperHook.enable(BlockDataWrapperHook.java:101) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.bukkit.common.component.LibraryComponentHolder.tryCreateAndEnableComponent(LibraryComponentHolder.java:110) [BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.bukkit.common.component.LibraryComponentSelector.update(LibraryComponentSelector.java:275) [BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.bukkit.common.internal.logic.BlockDataWrapperHook.<clinit>(BlockDataWrapperHook.java:23) [BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.bukkit.common.internal.CommonPlugin.enable(CommonPlugin.java:676) [BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:845) [BKCommonLib-1.19.2-v3-1410.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) [JavaPlugin.class:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:318) [JavaPluginLoader.class:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) [SimplePluginManager.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:477) [CraftServer.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:418) [CraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:340) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:315) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
[10:53:43] [Server thread/ERROR] [Mohist]: Failed to enable the default component
java.lang.NoClassDefFoundError: Could not initialize class com.bergerkiller.bukkit.common.wrappers.BlockDataRegistry
	at com.bergerkiller.bukkit.common.internal.logic.BlockDataWrapperHook.enable(BlockDataWrapperHook.java:101) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.bukkit.common.component.LibraryComponentSelector.enableDefaultComponent(LibraryComponentSelector.java:323) [BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.bukkit.common.component.LibraryComponentSelector.update(LibraryComponentSelector.java:291) [BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.bukkit.common.internal.logic.BlockDataWrapperHook.<clinit>(BlockDataWrapperHook.java:23) [BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.bukkit.common.internal.CommonPlugin.enable(CommonPlugin.java:676) [BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:845) [BKCommonLib-1.19.2-v3-1410.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) [JavaPlugin.class:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:318) [JavaPluginLoader.class:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) [SimplePluginManager.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:477) [CraftServer.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:418) [CraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:340) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:315) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
`


Peace!

**Comment by bergerkiller** [comment]
I loaded up the latest mohist 1.16.5 server build and downloaded the pixelmon mod off forge. Running cleanlight (from console) worked correctly. There were a few warnings and pixelmon spammed some errors at startup, but thats all.

Perhaps the dev build already fixed it? https://ci.mg-dev.eu/job/BKCommonLib/1422/

**Comment by Eisenbahn** [comment]
Oh, I'm using Mohist 1.12 as in the first pic I've sent
Should i still try that dev build version?

**Comment by bergerkiller** [comment]
Yeah just in case. Ill check 1.12.2 mohist as well

**Comment by Eisenbahn** [comment]
Same issue, sadly:

![image](https://user-images.githubusercontent.com/2753064/205360015-2bda49b8-a194-4c0f-b376-a8c8ce75158b.png)

this is my plugin list:
![image](https://user-images.githubusercontent.com/2753064/205360289-3b84a647-b886-43a4-b03c-53a349a06fb6.png)

**Comment by bergerkiller** [comment]
Can you send your full server log? Maybe as attachment?

**Comment by Eisenbahn** [comment]
There
[latest-Eisenbahnn-mohist112.zip](https://github.com/bergerhealer/Light-Cleaner/files/10143459/latest-Eisenbahnn-mohist112.zip)

**Comment by bergerkiller** [comment]
Theres quite a lot going wrong, not just in bkcl but also in the server itself / bukkit. Might want to report some of that to mohist devs, tho idk.

This tries to fix one of the problems that impacted bkcl, but there might be more issues. If it doesnt work, send another server log. https://ci.mg-dev.eu/job/BKCommonLib/1423/

**Comment by Eisenbahn** [comment]
![image](https://user-images.githubusercontent.com/2753064/205363937-57714974-1d52-455f-9280-1c13332da7b3.png)


```
[18:40:57] [Server thread/ERROR] [Mohist]: Failed to enable component '[1.8 AND LATER]' of BKCommonLib.BlockDataWrapperHook
java.lang.NoClassDefFoundError: Could not initialize class com.bergerkiller.bukkit.common.wrappers.BlockDataRegistry
	at com.bergerkiller.bukkit.common.internal.logic.BlockDataWrapperHook.enable(BlockDataWrapperHook.java:101) ~[BKCommonLib-1.19.2-v4-SNAPSHOT-1423.jar:?]
	at com.bergerkiller.bukkit.common.component.LibraryComponentHolder.tryCreateAndEnableComponent(LibraryComponentHolder.java:110) [BKCommonLib-1.19.2-v4-SNAPSHOT-1423.jar:?]
	at com.bergerkiller.bukkit.common.component.LibraryComponentSelector.update(LibraryComponentSelector.java:275) [BKCommonLib-1.19.2-v4-SNAPSHOT-1423.jar:?]
	at com.bergerkiller.bukkit.common.internal.logic.BlockDataWrapperHook.<clinit>(BlockDataWrapperHook.java:23) [BKCommonLib-1.19.2-v4-SNAPSHOT-1423.jar:?]
	at com.bergerkiller.bukkit.common.internal.CommonPlugin.enable(CommonPlugin.java:686) [BKCommonLib-1.19.2-v4-SNAPSHOT-1423.jar:?]
	at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:845) [BKCommonLib-1.19.2-v4-SNAPSHOT-1423.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) [JavaPlugin.class:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:318) [JavaPluginLoader.class:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) [SimplePluginManager.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:477) [CraftServer.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:418) [CraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:340) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:315) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
[18:40:57] [Server thread/ERROR] [Mohist]: Failed to enable the default component
java.lang.NoClassDefFoundError: Could not initialize class com.bergerkiller.bukkit.common.wrappers.BlockDataRegistry
	at com.bergerkiller.bukkit.common.internal.logic.BlockDataWrapperHook.enable(BlockDataWrapperHook.java:101) ~[BKCommonLib-1.19.2-v4-SNAPSHOT-1423.jar:?]
	at com.bergerkiller.bukkit.common.component.LibraryComponentSelector.enableDefaultComponent(LibraryComponentSelector.java:323) [BKCommonLib-1.19.2-v4-SNAPSHOT-1423.jar:?]
	at com.bergerkiller.bukkit.common.component.LibraryComponentSelector.update(LibraryComponentSelector.java:291) [BKCommonLib-1.19.2-v4-SNAPSHOT-1423.jar:?]
	at com.bergerkiller.bukkit.common.internal.logic.BlockDataWrapperHook.<clinit>(BlockDataWrapperHook.java:23) [BKCommonLib-1.19.2-v4-SNAPSHOT-1423.jar:?]
	at com.bergerkiller.bukkit.common.internal.CommonPlugin.enable(CommonPlugin.java:686) [BKCommonLib-1.19.2-v4-SNAPSHOT-1423.jar:?]
	at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:845) [BKCommonLib-1.19.2-v4-SNAPSHOT-1423.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) [JavaPlugin.class:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:318) [JavaPluginLoader.class:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) [SimplePluginManager.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:477) [CraftServer.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:418) [CraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:340) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:315) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
[18:41:00] [Server thread/INFO] [Mohist]: [BKCommonLib] We did what our big brother couldn't
[18:41:00] [Server thread/INFO] [Mohist]: [BKCommonLib] BKCommonLib version 1.19.2-v4-SNAPSHOT (build: 1423) enabled! (3.4s)
```

**Comment by Eisenbahn** [comment]
First is result when i try /cleanlight
Second is the BKC loading logs. I can send you the entire log again

**Comment by bergerkiller** [comment]
yeah I need the entire log because the actual error I need is elsewhere in the log

**Comment by Eisenbahn** [comment]
[Eisenbahnn-mohist-112-log2.zip](https://github.com/bergerhealer/Light-Cleaner/files/10143581/Eisenbahnn-mohist-112-log2.zip)

**Comment by bergerkiller** [comment]
https://ci.mg-dev.eu/job/BKCommonLib/1424/ lets give this a try...

**Comment by bergerkiller** [comment]
oh I broke it worse, gimme a sec

**Comment by Eisenbahn** [comment]
Still same error when using the command
![image](https://user-images.githubusercontent.com/2753064/205419213-e47471e1-fcbd-4f2e-95e0-2073ace143aa.png)

[latestmohist.zip](https://github.com/bergerhealer/Light-Cleaner/files/10145479/latestmohist.zip)

**Comment by bergerkiller** [comment]
This is going to take a while, but there is progress. https://ci.mg-dev.eu/job/BKCommonLib/1426/

**Comment by Eisenbahn** [comment]
Woah! I was loosing my hope. Look it's all good now!
Well done!
LMK if you have a Donation Gateway so i can send a small incentive

And thank you again!

**Comment by bergerkiller** [comment]
I do have a donation link you want to pass something small my way :)
https://www.paypal.com/paypalme/teambergerhealer

Good to hear it got resolved, I expected a few more cycles of fixes
