### ISSUE TITLE
[Bug] World does not stoke block light data

### ISSUE THREAD

**Issue by iPanic-Dev** [bergerhealer/Light-Cleaner#59]
### Issue
I mentioned this on the Discord quite some time ago, and haven't thought to come back to this until more recently I noticed my stop-gap (a script to pause the cleaning task) wasn't firing in time. Hoping to get this more permanently resolved. 

My understanding is it's a compatibility issue between the forge Starlight plugin, and Lightcleaner; but I could be wrong. 

Server is running `Arclight 1.18.2-1.0.7`, Starlight is `starlight-1.0.2+forge.546ae87`

### Logs

I've attached a snipped of what this error looks like. I can provide full console logs, but these spam for miles so it's quite the read. 

```
[Tue 03:06:33 ERROR LightCleaner] Failed to apply lighting
java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException: World does not store block light data
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
    at java.base/java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1498)
    at java.base/java.util.concurrent.CompletableFuture$CoCompletion.tryFire(CompletableFuture.java:1219)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
    at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
    at com.bergerkiller.bukkit.common.internal.logic.LightingHandler_1_14$EngineUpdateTaskLists.lambda$postRun$0(LightingHandler_1_14.java:265)
    at com.bergerkiller.bukkit.common.internal.CommonNextTickExecutor$ExecutorTask.run(CommonNextTickExecutor.java:163)
    at TRANSFORMER/arclight@1.18.2-1.0.7-40114eb5/org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:82)
    at TRANSFORMER/arclight@1.18.2-1.0.7-40114eb5/org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415)
    at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.handler$zcc000$arclight$runScheduler(MinecraftServerMixin.java:2381)
    at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m5703(MinecraftServerMixin.java)
    at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m5703(DedicatedServerMixin.java:326)
    at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m5705(MinecraftServerMixin.java:842)
    at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m130011(MinecraftServerMixin.java:2135)
    at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m177918(Minecra
[Tue 03:06:33 ERROR LightCleaner] Failed to apply lighting
java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException: World does not store block light data
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
    at java.base/java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1498)
    at java.base/java.util.concurrent.CompletableFuture$CoCompletion.tryFire(CompletableFuture.java:1219)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
    at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
    at com.bergerkiller.bukkit.common.internal.logic.LightingHandler_1_14$EngineUpdateTaskLists.lambda$postRun$0(LightingHandler_1_14.java:265)
    at com.bergerkiller.bukkit.common.internal.CommonNextTickExecutor$ExecutorTask.run(CommonNextTickExecutor.java:163)
    at TRANSFORMER/arclight@1.18.2-1.0.7-40114eb5/org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:82)
    at TRANSFORMER/arclight@1.18.2-1.0.7-40114eb5/org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415)
    at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.handler$zcc000$arclight$runScheduler(MinecraftServerMixin.java:2381)
    at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m5703(MinecraftServerMixin.java)
    at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m5703(DedicatedServerMixin.java:326)
    at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m5705(MinecraftServerMixin.java:842)
    at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m130011(MinecraftServerMixin.java:2135)
    at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m177918(Minecra

```

**Comment by iPanic-Dev** [comment]
Ignore the irony of my issue title...

**Comment by bergerkiller** [comment]
Hm yeah there is no support whatsoever for Starlight - the MOD. Only the paper starlight implementation. Its confusing because there are paper + forge hybrid servers which technically can do both.
